### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by egonw** [robbert-harms/mtt#1]
hi, not an issue and just a thank you. A colleague of mine (PhD candidate) made me aware of this template over on Overleaf and now passed it along to a few other PhDs. Are you still at UM? Seen https://twitter.com/OSCMaastricht / https://www.openscience-maastricht.nl/ ?

**Comment by robbert-harms** [comment]
hi egonw,

That is great to hear. I am happy that the thesis template is still useful. Feel free to share, adapt and use. 

I made the template because at the time there was none available and fellow Phd candidates were struggling with Latex templating. It already saw usage in 4 other theses since. 

At the moment I am no longer working at the UM, although I am still collaborating with my co-promotor on submitting a final paper from my thesis. 

If the template is so useful, maybe it would be nice if it were more widespread. Perhaps it is possible to put the template somewhere such that students can find it more easily? Perhaps on the UM website itself, or otherwise on openscience-maastricht.nl or twitter. I am unfamiliar with the latter, but feel free to mention the template on those platforms if you want. A reference to my name would be appreciated but is not obligatory. 

Best wishes,

Robbert Harms
